"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import Navbar from "@/components/navbar";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isHome = pathname === "/";

  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br from-gray-900 via-black to-gray-800 text-white min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Profilbild oben links */}
        <div className="fixed top-6 left-6 z-50">
          <Link href="/">
            <motion.div
              initial={
                isHome ? { scale: 1, x: 0, y: 0 } : { scale: 0.4, x: 0, y: 0 }
              }
              animate={
                isHome ? { scale: 1, x: 0, y: 0 } : { scale: 0.4, x: 0, y: 0 }
              }
              transition={{ duration: 0.8, ease: "easeInOut" }}
              className="cursor-pointer"
            >
              <Image
                src="/kibouakari.png"
                alt="Kibou"
                width={80}
                height={80}
                className="rounded-full shadow-md object-cover"
              />
            </motion.div>
          </Link>
        </div>

        {/* Navbar nur auf Subpages */}
        {!isHome && <Navbar />}

        {/* Animated Page Transitions */}
        <AnimatePresence mode="wait">
          <motion.main
            key={pathname}
            initial={{ opacity: 0, filter: "blur(8px)" }}
            animate={{ opacity: 1, filter: "blur(0px)" }}
            exit={{ opacity: 0, filter: "blur(8px)" }}
            transition={{ duration: 0.6, ease: "easeInOut" }}
            className="pt-32 px-6 md:px-12"
          >
            {children}
          </motion.main>
        </AnimatePresence>
      </body>
    </html>
  );
}
